apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: udagram-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
